{% set name = "autogluon.timeseries" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://github.com/autogluon/autogluon/archive/refs/tags/v{{ version }}.tar.gz
  # sha256: 96075e9bfce79420fe78a5566a1ba82f9a80598e955f4a4fc490f5561ede70bd
  # Use the latest commit temporarily
  url: https://github.com/autogluon/autogluon/archive/1f9f043fc03a878abca98a7abc5994e6ec82a0ab.tar.gz
  sha256: e1b29936eeab8f1a4298696598a13cc342db661f8c1d6490b969c85ca8d40469

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./timeseries -vv
  number: 4
  script_env:
   - RELEASE=1

requirements:
  host:
    - python >=3.8,<3.11
    - packaging
    - pip
  run:
    - python >=3.8,<3.11
    - joblib >=1.1,<2
    - numpy >=1.21,<1.27
    - scipy >=1.5.4,<1.12
    - pandas >=1.4.1,<1.6
    - statsmodels >=1.4.0,<1.5
    - gluonts >=0.12.0,<0.13
    - pytorch >=1.9,<1.14
    - pytorch-lightning >=1.7.4,<1.10.0
    - networkx >=2.3,<3.0
    - tqdm >=4.38,<5
    - ujson >=5,<6
    - sktime >=0.14,<0.16
    - pmdarima >=1.8.2,<1.9
    - tbats >=1.1,<2
    - autogluon.core =={{ version }}
    - autogluon.common =={{ version }}
    - autogluon.tabular =={{ version }}

test:
  imports:
    - autogluon.timeseries
  commands:
    - python -c "from autogluon.timeseries import __version__ as v; assert v == '{{ version }}', f'{v} != {{ version }}'"
  requires:
    - pip

about:
  home: https://pypi.org/project/autogluon.timeseries
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.  
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
    - Innixma
